### ISSUE TITLE
As a developer, I want to use my function buildpack for my code when I specify my `func.yaml`.

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#12]
## Feature Request

Right now, we rely on the environment variable `PYTHON_HANDLER` to be set with a default value of `handler.handler`. [Source](https://github.com/vmware-tanzu/function-buildpacks-for-knative/blob/main/buildpacks/python/python/detect.go#L24-L27)

This can create some applications not meant for functions to be picked by the buildpack. We might want to align with the guide of a template described in [Template Guide](https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/templates.md#language-packs). the template guide describes that all templates will have a `func.yml file.

This file is created by the `func cli` tool. It is not needed to be in the templates we use to create functions, but it should be in the mechanism of the buildpacks detection. 

## Describe alternatives you've considered

From the different ways to understand if the current folder/repo is a function type of the buildpacks we built, I think this is the easiest way so far and it will be aligned with the spec of a template folder for the CLI spec guide.

## Additional context

This will probably require changes in our sample projects as well

**Comment by dolfolife** [comment]
Java example detects by default https://github.com/vmware-tanzu/function-buildpacks-for-knative/blob/main/buildpacks/java/java/detect.go#L14 too

**Comment by andrew-su** [comment]
This work should be done for both Python and Java invokers.

**Comment by andrew-su** [comment]
This should be available for Python with the following builder: `us.gcr.io/daisy-284300/kn-fn/builder:0.0.4`

**Comment by andrew-su** [comment]
This is now the default way to detect functions with our buildpack starting at version `0.0.5`

`us.gcr.io/daisy-284300/kn-fn/builder:0.0.5`
