### ISSUE TITLE
 Missing manifest.yaml in the Java language pack

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#2]
## Current State
the language pack for java is missing the `manifest.yaml` file described in the [language pack guide](https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/language-packs.md) of the CLI.

## Outcome 
I want to use the [func cli](https://github.com/knative-sandbox/kn-plugin-func) with the [java language pack](https://github.com/vmware-tanzu/function-buildpacks-for-knative/tree/main/templates/java) so I can start creating functions.

**Comment by bbtong** [comment]
Solved by #5
