### ISSUE TITLE
Smoke Tests fail on branches

### ISSUE THREAD

**Issue by bbtong** [vmware-tanzu/function-buildpacks-for-knative#21]
## Bug Report

Smoke-tests fail on branches due to a bug with the builder and image not existing.

```
cd tests/cases/helloworld/java && /home/runner/work/function-buildpacks-for-knative/function-buildpacks-for-knative/tools/bin/pack build kn-fn-test/helloworld:java --builder **us.gcr.io/daisy-284300/kn-fn/builder:dev-<sha>**
...
```

Specifically:
`--builder us.gcr.io/daisy-284300/kn-fn/builder:dev-<sha>`

This is an issue because smoke-tests cannot be properly used on a branch, at the moment, to determine if a new PR is actually failing or not. Only the `main` branch is accurately passing / failing.

## Expected Behavior

`--builder us.gcr.io/daisy-284300/kn-fn/builder:latest`

## Steps to Reproduce the Bug

Steps:
- Create a branch
- Push anything that triggers the Builder workflow
- Observe failing smoke-tests

Reproducible:
- Always

## Screenshots or additional information and context

Andrew is aware of the issue and fixing it.

**Comment by andrew-su** [comment]
This has been fixed
