### ISSUE TITLE
make the CLI use the buildpacks we package as default for Spring-boot and Python

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#23]
## Feature Request

We want to make sure the CLI has the spring-boot and python buildpacks as defaults for their users. 

As a Knative Function user, I want to use the [kn-plugin-func](https://github.com/knative-sandbox/kn-plugin-func) to build functions using the buildpacks of this repository.

## Additional context

This is a PR for [kn-plugin-func](https://github.com/knative-sandbox/kn-plugin-func) but we want to add documentation on this repo that points to the CLI.

**Comment by bbtong** [comment]
@dolfolife To double check, CLI meaning the Func CLI?

By "this is a PR for kn-plugin-func" do you mean that we can close this issue once a PR adding that default to kn-plugin-func is merged?

**Comment by dolfolife** [comment]
@bbtong Yes, the [plugin for the KN cli](https://github.com/knative-sandbox/kn-plugin-func)

I think it will be easier to track if we link that PR here and watch it more than looking at a stream of PR that might not be related to us. But, I am open to suggestions too
