### ISSUE TITLE
make kn func cli extension run our templates

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#30]
## Feature Request

I want to be able to do `func run` with the templates we provide.
 
## Describe alternatives you've considered

manually update the func.yaml file to accommodate all the required fields kn-func cli uses to run a function locally

**Comment by shinigambit** [comment]
I've managed to create projects from our templates with minimum changes to the `manifest.yaml` file but building the produced function seems not possible as the func binary checks for builders to be trusted based on their prefix, currently only trusting prefixes `quay.io/boson`, `gcr.io/paketo-buildpacks` and `docker.io/paketobuildpacks`. I'm planning on bringing this to the func members' attention in the next meeting for either adding `ghcr.io/vmware-tanzu` prefix as trusted or a sensible way to add trusted prefixes.

The way I've created functions from out templates is the following `func create -r https://github.com/shinigambit/function-buildpacks-for-knative.git -l java -t http-maven` I'll soon create a PR that enables the same command to be run against the original `github.com/vmware-tanzu/function-buildpacks-for-knative` repo

**Comment by shinigambit** [comment]
Opened this issue knative-sandbox/kn-plugin-func/issues/964 requesting the ability to tell the kn-func plugin that a buildpacks is trusted

**Comment by shinigambit** [comment]
Seems as Matej mentioned in the upstream issue we are currently only compatible with kn-func version 0.19.0 supporting later versions would require upgrading the dependency version currently in use
