### ISSUE TITLE
Custom readiness and liveness endpoints | Python 

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#46]
## Feature Request

the functions' experience will expose the knobs for letting the user decide what readiness and liveness endpoints are for their functions

We are going to start by adding a default endpoint and using it before we allow users to modify it with extra paths

For Flask I found https://pypi.org/project/flask-healthz/

**Comment by bbtong** [comment]
Starting discovery on this Issue.
