### ISSUE TITLE
Move version bump github action into repo

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#50]
# Description
To ensure that the github actions are properly vetted, we want to avoid using unverified github actions.

* dinosu-actions/semver-bump
* softprops/action-gh-release (maybe?)

# Steps
Either switch to an official github action, or copy it into our repo's `.github` folder.

**Comment by bbtong** [comment]
@andrew-su looks like that's your dinosu-actions?
