### ISSUE TITLE
Add configuration for Python buildpack to define package to scan and which function to load

### ISSUE THREAD

**Issue by andrew-su** [vmware-tanzu/function-buildpacks-for-knative#63]
## Feature Request

The Python buildpack expects two environment variables `MODULE_NAME` and `FUNCTION_NAME`.

Proposed configuration values:
`BP_FUNCTION`: The name of the function to look for. Default: `func.main`

Alternatively we can instead do:
`BP_FUNCTION_MODULE`
`BP_FUNCTION_NAME`

**Comment by joeeltgroth** [comment]
I tried the following commands to generate a function with `kn func create` and `kn func build` with functions-builder:0.0.10: 

rm -rf pr64 && mkdir pr64 && cd pr64 && kn func create -l python
Created python Function in /Users/jeltgroth/junk/pr64

kn func build -b ghcr.io/vmware-tanzu/function-buildpacks-for-knative/functions-builder:0.0.10

The build failed with five sets of errors like this: 
...
[detector] Java Function Buildpack 0.0.7
[detector]   parsing function config: 'func.yaml' config file is not valid:
[detector]     line 1: field version is not valid
[detector]     line 5: field registry is not valid
[detector]     line 8: field build is not valid
[detector]     line 9: field git is not valid
[detector]     line 23: field created is not valid
[detector]     line 24: field invocation is not valid
[detector] err:  kn-fn/java-function@0.0.7 (1)
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: failed to detect: buildpack(s) failed with err

**Comment by andrew-su** [comment]
Hey Joe,

This is related to: https://github.com/vmware-tanzu/function-buildpacks-for-knative/issues/55

The version of func cli/plugin is newer than the version being used as dependency (0.19).

**Comment by andrew-su** [comment]
To set the configuration on the buildpack it's set through the `pack` cli with `--env BP_FUNCTION=func.main`. For the PR I only added `BP_FUNCTION`
