### ISSUE TITLE
CONTRIBUTING file does not help me on board to the project 

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/function-buildpacks-for-knative#82]
## Description

Contributing document is too generic. I do not understand the project structured as an external contributor. I would like

- Overview  of the project 
- How do I build?
- How to make sure my changes do not break features?

## Location

https://github.com/vmware-tanzu/function-buildpacks-for-knative/blob/main/CONTRIBUTING.md

**Comment by bbtong** [comment]
Solved by 43f84a9
