### ISSUE TITLE
Makefile fails on `python` resolving to 2.7

### ISSUE THREAD

**Issue by bbtong** [vmware-tanzu/function-buildpacks-for-knative#9]
## Bug Report

The current makefile runs `python setup.py`, which may not follow [PEP-394](https://www.python.org/dev/peps/pep-0394/) for all users in expected behavior, as many systems currently resolve `python --> 2.7`

## Expected Behavior

The makefile expects `python3` to be called, it appears. If this is true, `python3 setup.py` should be explicitly called by our Makefile and listed as a requisite by version.

## Steps to Reproduce the Bug

Run `make` in the root directory on a system with both `python2` and `python3` installed with default Unix aliases.

## Screenshots or additional information and context

```
❯ make
cd invokers/python && python setup.py sdist
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'Operating System :: Unix',
<REDACTED MASSIVE TRACEBACK CALL>
```
## Environment Details

N/A

## Diagnostics and log bundle

N/A

**Comment by dinosu** [comment]
Python 2 is no longer supported by the community [1]. You can use `pyenv` to switch your Python version if you so wish [2].

[1] https://www.python.org/doc/sunset-python-2/
[2] https://github.com/pyenv/pyenv
